# Generated by Django 5.0.3 on 2024-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_portfoliopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=50, verbose_name='Post holati'),
        ),
    ]
