# Generated by Django 5.0.3 on 2024-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_portfoliopost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_completed', models.IntegerField(default=0, verbose_name='Loyihalar soni')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='Yillik tajribasi')),
                ('total_clients', models.IntegerField(default=0, verbose_name='Mijozlar soni')),
                ('award_won', models.IntegerField(default=0, verbose_name='Mukofotlar soni')),
            ],
            options={
                'verbose_name': 'Statistikalar',
                'verbose_name_plural': 'Statistikalar',
                'db_table': 'Statistics_Page',
                'managed': True,
            },
        ),
    ]
