# Generated by Django 5.0.3 on 2024-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_statisticspage_works_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticspage',
            name='works_completed',
            field=models.IntegerField(default=0, verbose_name='Loyihalar soni'),
        ),
    ]
