# Generated by Django 5.0.3 on 2024-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_statisticspage_works_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(choices=[('ion-monitor', 'Web Design'), ('ion-code-working', 'Web Development'), ('ion-camera', 'Photography'), ('ion-android-phone-portrait', 'Responsive Design'), ('ion-paintbrush', 'Graphic Design'), ('ion-stats-bars', 'Marketing Services')], upload_to='', verbose_name='Logo')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('about', models.TextField(verbose_name=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='Deactive', max_length=50)),
            ],
            options={
                'verbose_name': 'Xizmatlar',
                'verbose_name_plural': 'Xizmatlar',
                'db_table': 'Services_Pages',
                'managed': True,
            },
        ),
    ]
