# Generated by Django 5.0.3 on 2024-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_servicespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='about',
            field=models.TextField(verbose_name='Haqida'),
        ),
    ]
