# Generated by Django 5.0.3 on 2024-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_servicespage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=50),
        ),
    ]
