# Generated by Django 5.0.3 on 2024-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_servicespage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Rasmi')),
                ('name', models.CharField(max_length=50, verbose_name='Ism familiyasi')),
                ('about', models.TextField(verbose_name='Haqida')),
                ('status', models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=50, verbose_name='Post holati')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoa',
                'db_table': 'Team_page',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='portfoliopost',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=50, verbose_name='Post holati'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=50),
        ),
    ]
