# Generated by Django 5.0.3 on 2024-04-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_teampage_alter_portfoliopost_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism familiya')),
                ('profile', models.CharField(max_length=250, verbose_name='Mutaxasisligi')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(upload_to='me/', verbose_name='Rasmi')),
                ('content', models.TextField(verbose_name='Haqida')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchi',
                'db_table': 'About_Me_Page',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField(default=0, null=True, verbose_name='Foiz')),
                ('about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.aboutmepage')),
            ],
            options={
                'verbose_name': 'Mahorat',
                'verbose_name_plural': 'Mahorat',
                'db_table': 'Skill',
                'managed': True,
            },
        ),
    ]
