# Generated by Django 5.0.3 on 2024-04-07 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_aboutmepage_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='about_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to='blog.aboutmepage'),
        ),
    ]
