# Generated by Django 5.0.3 on 2024-04-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogdetailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='blog/', verbose_name='Post rasmi')),
                ('name', models.CharField(max_length=250, verbose_name='Post nomi')),
                ('content', models.TextField(verbose_name="Post haqida qisqacha ma'lumot")),
                ('about', models.TextField(verbose_name="Post haqida to'liq ma'lumot")),
                ('user_photo', models.ImageField(upload_to='blog/', verbose_name='Foydalanuvchi rasmi')),
                ('user_fullname', models.CharField(max_length=50, verbose_name='Foydalanuvchi ism familiyasi')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=50)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog post',
                'db_table': 'Blog_Page',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='BlogDetailPage',
        ),
    ]
