# Generated by Django 5.0.3 on 2024-04-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_blogpage_blogdetailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism Familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='comment-image/user.jpg', upload_to='comment-image/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogdetailpage')),
            ],
            options={
                'verbose_name': 'Izohlar',
                'verbose_name_plural': 'Izohlar',
                'db_table': 'Comment_Page',
                'managed': True,
            },
        ),
    ]
