# Generated by Django 5.0.3 on 2024-04-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_commentpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetailpage',
            options={'managed': True, 'ordering': ['-date'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog post'},
        ),
        migrations.AlterField(
            model_name='commentpage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
