# Generated by Django 5.0.3 on 2024-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogdetailpage_options_alter_commentpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Eslatma uchun'),
        ),
    ]
