# Generated by Django 5.0.3 on 2024-04-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogdetailpage_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='note',
        ),
    ]
