# Generated by Django 5.0.3 on 2024-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blogdetailpage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Eslatma uchun'),
        ),
    ]
